---
# role: jomrr.openssh
# file: .pre-commit-config.yaml

repos:
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v26.8.0
    hooks:
      - id: ansible-lint
        always_run: false
        entry: ansible-lint --force-color --offline --profile production .
        language: python
        pass_filenames: false
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check library tests
        language: python
        additional_dependencies:
          - ansible-core>=2.20
          - mypy
          - ruff
          - pylint
        pass_filenames: false
        types:
          - python
        always_run: true
      - id: mypy
        name: mypy
        entry: mypy --follow-untyped library tests
        language: python
        additional_dependencies:
          - ansible-core>=2.20
          - mypy
          - ruff
          - pylint
        pass_filenames: false
        types:
          - python
        always_run: true
      - id: pylint
        name: pylint
        entry: pylint library tests
        language: python
        additional_dependencies:
          - ansible-core>=2.20
          - mypy
          - ruff
          - pylint
        pass_filenames: false
        types:
          - python
        always_run: true
      - id: moduli-tests
        name: moduli-tests
        entry: python -m unittest discover -s tests
        language: python
        additional_dependencies:
          - ansible-core>=2.20
          - mypy
          - ruff
          - pylint
        pass_filenames: false
        types:
          - python
        always_run: true
