---
# role: openssh
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        openssh_authorized_keys:
          - user: "openssh-test"
            key: "{{ lookup('ansible.builtin.file', lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') + '/keys/client.pub')\
              \ }}"
          - user: "root"
            key: "{{ lookup('ansible.builtin.file', lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') + '/keys/client.pub')\
              \ }}"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-openssh"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
  - name: "debian-latest-openssh"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
  - name: "fedora-latest-openssh"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
  - name: "opensuse-leap-latest-openssh"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
  - name: "opensuse-tumbleweed-latest-openssh"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
  - name: "ubuntu-latest-openssh"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    capabilities:
      - "DAC_READ_SEARCH"
