---
# role: openssh
# file: molecule/resources/playbooks/converge.yml

- name: "Molecule | converge | openssh"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
